// Builds the optional chunks of the static site: the JavaScript that the game only
// needs sometimes, kept out of dist/web/main.js so that it never delays the first
// rendering of the page. Each chunk is a classic script (Chromium 37 cannot parse
// ES modules) that registers the modules it provides on the global channel that
// src/js/optional-chunks.js sets up, and the service worker caches the chunks in the
// background (see src/web/service-worker.js).
import * as esbuild from 'esbuild';
import fs from 'node:fs/promises';
import path from 'node:path';
import {createBabelPlugin, webBabelTargets} from './bundle.mjs';
import {optionalChunkName} from '../src/js/optional-chunk-names.js';
import {buildDirectory, rootDirectory, webDistDirectory} from './site.mjs';

const chunkSourceDirectory = path.join(buildDirectory, 'optional-chunks');

// Every specifier that a build of main.js tried to import dynamically, collected by
// the patch of scripts/bundle.mjs.
export function createOptionalSpecifierCollector() {
	return new Set();
}

async function isInstalled(specifier) {
	try {
		await import.meta.resolve(specifier);
		return true;
	} catch (error) {
		return false;
	}
}

// A chunk is generated as an ES module that imports what it provides and registers it
// on the channel of the loader; the build then turns it into a classic script.
function chunkSourceFor(specifiers) {
	const lines = [
		'// Generated by scripts/optional-chunks.mjs. The chunk of the static site that',
		'// provides the modules below; see src/js/optional-chunks.js for the loader.',
	];
	specifiers.forEach((specifier, index) => {
		lines.push(`import * as optionalModule${index} from ${JSON.stringify(specifier)};`);
	});
	lines.push('');
	specifiers.forEach((specifier, index) => {
		lines.push(`globalThis.SunniesnowOptional.register(${JSON.stringify(specifier)}, optionalModule${index});`);
	});
	lines.push('');
	return lines.join('\n');
}

export async function buildOptionalChunks({specifiers, development}) {
	const chunks = new Map();
	const missing = [];
	for (const specifier of [...specifiers].sort()) {
		if (!await isInstalled(specifier)) {
			missing.push(specifier);
			continue;
		}
		const name = optionalChunkName(specifier);
		chunks.set(name, [...(chunks.get(name) ?? []), specifier]);
	}
	for (const specifier of missing) {
		console.warn(`Warning: ${specifier} is not installed, so the site will report an error when it is needed`);
	}
	const chunkDirectory = path.join(webDistDirectory, 'optional');
	await fs.rm(chunkDirectory, {recursive: true, force: true});
	await fs.mkdir(chunkDirectory, {recursive: true});
	await fs.rm(chunkSourceDirectory, {recursive: true, force: true});
	await fs.mkdir(chunkSourceDirectory, {recursive: true});
	const names = [];
	for (const [name, chunkSpecifiers] of chunks) {
		const source = path.join(chunkSourceDirectory, `${name}.js`);
		await fs.writeFile(source, chunkSourceFor(chunkSpecifiers));
		await esbuild.build({
			entryPoints: [source],
			outfile: path.join(chunkDirectory, `${name}.js`),
			bundle: true,
			format: 'iife',
			platform: 'browser',
			target: 'es5',
			plugins: [createBabelPlugin({targets: webBabelTargets})],
			minify: !development,
			legalComments: 'eof',
			sourcemap: false,
			logLevel: 'warning',
		});
		names.push(`${name}.js`);
	}
	// The service worker reads this manifest to know what to cache in the background.
	await fs.writeFile(
		path.join(chunkDirectory, 'manifest.json'),
		`${JSON.stringify({chunks: names}, null, '\t')}\n`
	);
	console.log(`Built ${names.length} optional chunk(s) in ${path.relative(rootDirectory, chunkDirectory)}: ${names.join(', ')}`);
	return names;
}
